# SITE CONFIGURATION
baseurl: ""
url: "https://mengcuilab.github.io"


# THEME-SPECIFIC CONFIGURATION
title: Cui Research Group
avatar: /assets/img/logos/purdue_round.jpg


# Header and footer text
header_text:  
header_feature_image: /assets/img/fish.png

